Improve build_ext

diff --git a/drivers/linux/Makefile b/drivers/linux/Makefile
--- a/drivers/linux/Makefile
+++ b/drivers/linux/Makefile
@@ -1,41 +1,30 @@
-KERNEL_SRC_DIR = /lib/modules/`uname -r`/build 
-##KERNEL_SRC_DIR = /usr/src/android/3.0-mid
-
-EXTRA_CFLAGS = 
-VERSION=
-
-#obj-m += chipsec.o
+KERNEL_SRC_DIR ?= /lib/modules/`uname -r`/build
+#KERNEL_SRC_DIR = /usr/src/android/3.0-mid
 
 ifeq ($(ARCH),i386)
-obj-m += chipsec.o
-chipsec-objs := chipsec_km.o i386/cpu.o
-all:	clean chipsec32
+elf-size := elf32
+asm-path := i386
 else
-obj-m += chipsec.o
-chipsec-objs := chipsec_km.o amd64/cpu.o
-all:	clean chipsec64
+elf-size := elf64
+asm-path := amd64
 endif
 
-chipsec64: clean
-	nasm -f elf64 -o amd64/cpu.o amd64/cpu.asm;
-	make -C $(KERNEL_SRC_DIR) SUBDIRS=`pwd` modules
-	make -C ../../chipsec/helper/linux/
-	cp chipsec.ko ../../chipsec/helper/linux/
+chipsec-objs := chipsec_km.o $(asm-path)/cpu.o
+obj-m += chipsec.o
 
-chipsec32: clean
-	nasm -f elf32 -o i386/cpu.o i386/cpu.asm;
-	make -C $(KERNEL_SRC_DIR) SUBDIRS=`pwd` modules
-	make -C ../../chipsec/helper/linux/
-	cp chipsec.ko ../../chipsec/helper/linux/
+all: chipsec
 
-install:
-	./run.sh
+check_kernel_dir:
+	@if [ ! -d $(KERNEL_SRC_DIR) ]; then \
+		echo "Unable to find the Linux source tree."; \
+		exit 1; \
+	fi
 
-uninstall:
-	rmmod chipsec
+chipsec: check_kernel_dir clean
+	nasm -f $(elf-size) -o $(asm-path)/cpu.o $(asm-path)/cpu.asm
+	make -C $(KERNEL_SRC_DIR) SUBDIRS=${CURDIR} modules
 
-clean:
-	rm -f *.o *.ko *.mod.c Module.symvers Module.markers modules.order \.*.o.cmd \.*.ko.cmd \.*.o.d
-	rm -rf \.tmp_versions
-	rm -rf amd64/cpu.o i386/cpu.o
+clean: check_kernel_dir
+	make -C $(KERNEL_SRC_DIR) SUBDIRS=${CURDIR} clean
+	rm -f ${asm-path}/cpu.o
 
